version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.11.5-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    networks:
      - backend
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

networks:
  backend:
    name: rabbitmq